services:
  allure:
    build: .
    container_name: test-report-server
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3443:3443"
    environment:
      REPORTS_ROOT: /app/reports
      PORT: "3000"
      USE_HTTPS: "1"
      HTTPS_PORT: "3443"
      SSL_CERT_PATH: /app/cert/cert.pem
      SSL_KEY_PATH: /app/cert/key.pem
    volumes:
      - /var/jenkins/test/output:/app/reports:ro
      - ./cert:/app/cert
    networks:
      - jenkins_network
 
networks:
  jenkins_network:
    external: true